Implement file bundling in remaining contraction modules with output
aportelli/Hadrons pull request #104
Opened 2023-02-10 15:43 UTC by RChrHill

Adds file bundling features to the remaining contraction modules with file outputs, as has been done with the Meson and WeakNonEye modules.

2023-04-04 11:18 UTC, aportelli commented
Is this ready to go?

2023-04-04 11:30 UTC, RChrHill commented
> Is this ready to go?

This is ready - apologies, was waiting for the coverage tests to complete before unmarked as draft

2023-04-05 16:56 UTC, aportelli requested changes
Thanks it looks great, I'll work on having that in `develop` ASAP and used in future production. I have some minor requests, please see below and tick as completed.

- [ ] Please address comments in code
- [ ] Please always use braces after `if`/`else`
- [ ] Please write function calls as `f(x)` not `f( x )`

2023-04-05 16:56 UTC, aportelli commented on Hadrons/DistilMatrix.hpp
> +    typedef Hadrons::DistillationNoise<FImpl> DistillationNoise;
Why is this necessary?

2023-04-05 16:56 UTC, aportelli commented on Hadrons/Global.hpp
> -typedef Solver<FImpl> Solver##suffix;
Why is this necessary?

2023-04-07 15:00 UTC, merged