Feat/TopologicalCharge
aportelli/Hadrons pull request #108
Opened 2023-03-14 18:58 UTC by fjosw

I started implementing a new module which can compute the topological charge using the Wilson flow. At the moment the module uses an adaptive integrator, Grid also has a standard integrator which could be used alternatively.

For now, the output is only printed to the log.

2023-03-15 18:09 UTC, aportelli commented
Hi @fjosw thanks this is a great addition. Could you add something that output the result to disk please (it can be a single number HDF5)? My convention is to assume that the primary source of results are files on disk, not the log (although a number of modules show results of part of it in the log). Thanks

2023-03-15 21:34 UTC, fjosw commented
I thought a bit more about the output today and I could imagine outputting both, the energy density and the topological charge, as a function of the flow time instead of just outputting the charge at the final flow time. This would also facilitate the extraction of $t_0$ and $w_0$. If we go down that route a name like `FlowObservables` would maybe better describe the module.

2023-03-30 08:39 UTC, fjosw commented
I have put this PR on hold for now as Chris Kelly has made relevant changes to the Wilson Flow functionality on the `dirichlet` branch which Peter intends to merge soon (https://github.com/paboyle/Grid/pull/412). An example of the new functionality can for example be found [here](https://github.com/giltirn/Grid_meas/blob/master/common/wilson_flow.h).

2023-04-04 16:36 UTC, fjosw commented
I adopted the model to the recent changes from the `dirichlet` branch, implemented the computation of the flow observables at each step of the Wilson flow smearing and added an hdf5 output to the module.

2023-04-05 17:23 UTC, aportelli requested changes
Thanks, it looks ready to go. Please see one minor comment. Could you please confirm that you checked it does serialize to a 2D HDF5 array?

2023-04-05 17:23 UTC, aportelli commented on Hadrons/Modules/MGauge/FlowObservables.hpp
> + *                         FlowObservables                                 *
Please correct spacing a put more comprehensive on-liner description

2023-04-05 19:21 UTC, fjosw commented
I  improved the header comment.

The output does not serialize to a 2D array but instead to four 1D arrays with separate descriptions. I followed up on Simon's suggestion and prioritized verbosity over memory efficiency. One would typically only compute the output once per configuration and the file size is about 20k for typical flow times so I think memory overhead is not a concern here.

2023-04-05 20:47 UTC, aportelli commented
Good with me, thanks!

2023-04-05 20:47 UTC, merged