Local Coherence Deflation
aportelli/Hadrons pull request #109
Opened 2023-03-21 12:57 UTC by rrhodgson

Here is the proposal for the overhaul of the deflation setup and adding the local coherence (coarse) deflation.
Requires Grid PR [#426](https://github.com/paboyle/Grid/pull/426) to be accepted first.

Includes:
- Eigenpack compressor/decompressor
- Add coarse deflation
- Make source casting its own module
- Combine bathed and non-batched version of modules
- Removed reloading batched deflation
- Add batched mixed precision solver

2023-04-05 17:20 UTC, aportelli requested changes
Thanks this is really great, please address the changes below. I will merge in `develop` once we have more visibility about fixes needed (or not) after Grid's `feature/dirichlet` merge.
- [ ] please address comments in code
- [ ] please use `name_` only for private variables and not function arguments

2023-04-05 17:20 UTC, aportelli commented on Hadrons/Modules/MUtilities/EigenPackLCCompress.hpp
> + *                    Local coherence Lanczos eigensolver                     *
Fix comment

2023-04-05 17:20 UTC, aportelli commented on Hadrons/Modules/MUtilities/EigenPackLCDecompress.hpp
> + *                    Local coherence Lanczos eigensolver                     *
Fix comment

2023-04-06 15:08 UTC, rrhodgson commented
Thanks for the comments. They should be fixed now.
I also changed the `evBatchSize` back to 1. It will run exactly the same but gives more verbose debug output

2023-04-06 15:38 UTC, aportelli approved these changes
Thanks! All good

2023-04-07 10:27 UTC, merged